version: "3.8"

services:
  article-service:
    image: happyheadlines/article-service:week39

  comment-service:
    image: happyheadlines/comment-service:week39

  profanity-service:
    image: happyheadlines/profanity-service:week39

  draft-service:
    image: happyheadlines/draft-service:week39

  observability:
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /otel-lgtm/grafana/conf/provisioning/dashboards/custom/happy-headlines-overview.json
    configs:
      - source: grafana_dashboard_provider
        target: /otel-lgtm/grafana/conf/provisioning/dashboards/custom.yaml
      - source: grafana_dashboard_overview
        target: /otel-lgtm/grafana/conf/provisioning/dashboards/custom/happy-headlines-overview.json

configs:
  grafana_dashboard_provider:
    file: ./infra/grafana/dashboards.yml
  grafana_dashboard_overview:
    file: ./infra/grafana/happy-headlines-overview.json
